//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.02 at 02:03:29 PM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.zaripov.com/ws/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)

package ru.geekbrains.Market.soap.product;
